version: '3.7'
services:

  #-----------------------------------------------------
  # proxy
  #-----------------------------------------------------
  srv-proxy:
    container_name: proxy
    image: nginx:1.22.1
    restart: always
    networks:
      - net-backend
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/config:/etc/nginx/conf.d
      - ./nginx/home:/home
    depends_on:
      - srv-k43-wordpress
      - srv-arcade-k43

  #-----------------------------------------------------
  # wordpress
  #-----------------------------------------------------
  srv-k43-wordpress:
    container_name: k43-wordpress
    image: wordpress:6.1.1-php8.1-apache
    restart: always
    networks:
      - net-backend
      - net-mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: ${K43_WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${K43_WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${K43_WORDPRESS_DB_PASSWORD}
    volumes:
      - ./wordpress/html:/var/www/html
    depends_on:
      - srv-mysql

  #-----------------------------------------------------
  # database
  #-----------------------------------------------------
  srv-mysql:
    container_name: mysql
    image: mysql:8.0
    restart: always
    networks:
      - net-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${K43_ROOT_DB_PASSWORD}
    volumes:
      - vol-mysql:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

  #  srv-phpmyadmin:
  #    image: phpmyadmin/phpmyadmin
  #    container_name: phpmyadmin
  #    networks:
  #      - net-mysql
  #      - net-backend
  #    environment:
  #      PMA_ARBITRARY: 1
  #    restart: always

  srv-arcade-k43:
    container_name: arcade-k43
    image: dominikdarocha/arcade-k43:stable
    restart: always
    networks:
      - net-backend
    volumes:
      - ./arcade-43/config:/opt/arcade-k43/config
    depends_on:
      - srv-mysql

networks:
  net-backend:
  net-mysql:


volumes:
  vol-mysql:
