FROM wordpress:6.1.1-php8.1-apache

WORKDIR /var/www/html/
COPY ./wordpress/html/wp-content/uploads/.htaccess ./wp-content/uploads/.htaccess
COPY ./wordpress/html/wp-content/uploads/protect-uploads.php ./wp-content/uploads/protect-uploads.php

